# HUDM 5001 — Programming for Data Science
## Session 03 · Python Intro: Operators, Input/Output & NumPy
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/cgpan/hudm5001/blob/main/Week_03/03_Operators_IO_Numpy.ipynb)  

Version: 09.22.2026 with minor bugs fixed.

[**Chenguang Pan**](https://cpan.ai/), [**Youmi Lab**](https://youmilab.ai/)  
**Teachers College, Columbia University**   

> ▶️ **Please disable the generative AI feature first** —   
> If you are using Colab, follow Edit --> Notebook settings --> AI Assistance, and check the box `Hide generative AI features`.  
> Then **run the Setup cell first** (▶ or `Shift+Enter`). Everything else runs top-to-bottom.  
   
About this notebook:  
This notebook is adapted from Prof. Youmi Suk's materials for HUDM 5001, Programming for Data Science ([original repository](https://github.com/youmilab/hudm5001)).  
Wording in this notebook was refined with Claude. I am responsible for its accuracy.

Three building blocks today. **Operators** let us *compute* with values. **Input/Output** lets us *read and write* files (text, JSON, CSV). And **NumPy** gives us the fast numeric arrays that all of scientific Python is built on.

---
## 1. Big Picture

### 🎯 Learning Objectives
By the end of this session you will be able to:
- Use arithmetic (`+ - * / // % **`), comparison, logical, membership, and identity operators.
- Read and write **text**, **JSON**, and **CSV** files using `open()` / `with`.
- Manage paths safely with the `os` / `os.path` module.
- Create **NumPy `ndarray`s** and understand *vectorized*, element-wise operations.
- Index, slice, and **boolean-index** arrays; compute summary statistics.

### ✅ Prerequisites
- Week 2 (data types, variables).
- Run the Setup cell to import numpy & pandas.

### 🧩 Key Concepts
`arithmetic`  `comparison`  `logical`  `identity (`is`)`  `membership (`in`)`  `file modes`  `JSON`  `CSV`  `ndarray`  `vectorization`  `boolean indexing`

### 📖 Reading
- McKinney, *Python for Data Analysis*, Chapter 4 (NumPy basics)

### 🗺️ Today's Agenda
1. Operators: arithmetic, comparison, logical, identity, membership
2. Input/Output: text, JSON, CSV files; `with open(...)`
3. Paths with `os.path`
4. NumPy motivation & the ndarray
5. Array creation, math, indexing, slicing, boolean indexing

---
## ▶️ Setup — run this cell first
This installs anything Colab is missing, imports the libraries we'll use, and sets `DATA_BASE`
(the address of the course data on GitHub).

In [1]:
# === SETUP — run me first! ===
import numpy as np
import pandas as pd
import json, os

# Course data is read straight from the public course repo on GitHub,
# so these notebooks run anywhere (Colab, Jupyter, locally) with no downloads.
DATA_BASE = "https://raw.githubusercontent.com/cgpan/hudm5001/main/asset"
print("Setup complete ✅  — data base URL:", DATA_BASE)

Setup complete ✅  — data base URL: https://raw.githubusercontent.com/cgpan/hudm5001/main/asset


---
## 2. Content

### 2.1 Operators
**Arithmetic.** Beyond `+ - * /`, note three you may not know:
- `//` **floor division** (divide and round *down*): `5//2` is `2`, raher than `2.5` or `3`.
- `%` **modulus** (the remainder),
- `**` **exponentiation**.

In [ ]:
print(5 / 2)    # 2.5  (true division -> always float)
print(5 // 2)   # 2    (floor division)
print(-5 // 2)  # -3   (rounds DOWN, toward negative infinity)

In [ ]:
print(5 % 2)    # 1    (remainder -> great for 'is it even/odd?')
print(5 ** 3)   # 125  (5 cubed)

The remainder operator is commonly used in the iteration monitoring process.

**Comparison** operators return a `bool`: `==  !=  <  <=  >  >=`.  
- `A == B`: whether A equals B.  
- `A != B`: whether A is not equal to B.
**Logical** operators combine bools: `and  or  not`.

In [ ]:
x = 10
print(0 == (10 % 5))            # True  (10 % 5 == 0)
print(5/9 != 0.5555)           # True
print((x % 10 == 0) and (x < -1))   # False
print(not x == 5)              # True

**Identity** `is` / `is not` asks *"the same object in memory?"* — different from `==` (*"the same value?"*).  
- `==` is about the value equality  
- `is` is to check the object identity
**Membership** `in` / `not in` tests if a value is inside a container.

In [ ]:
x = ['python', 'R']
y = ['python', 'R']     # same contents, different object
print(x == y)           # True  -> equal values
print(x is y)           # False -> NOT the same object

In [ ]:
print(f"The RAM id address for X is {id(x)}")
print(f"The RAM id address for Y is {id(y)}")

In [ ]:
print('fries' in ['fries', 'burger'])     # True
print('chicken' not in ['fries', 'burger'])  # True

#### ✏️ Try It Yourself — Exercise 1

Q1: 137 minutes is how many whole hours and leftover minutes?  
**Difficulty:** ★★★☆☆  **Skills:** `floor & modulus (split a quantity)`

In [2]:
# your code here
whole_hours = 137//60
left_minute=137%60
print(f'137 minute is {whole_hours} whole hours and {left_minute} leftover minutes')

137 minute is 2 whole hours and 17 leftover minutes


Q2: is 339 even? Your printed results should be the `Even? False` and `Odd? True`. You must use the `==` and `%`. `f.string` is optional.   
**Difficulty:** ★☆☆☆☆  **Skills:** `==` and `%`

In [3]:
# your code here
if 339%2 == 0:
  print('339 is even')
else:
  print('339 is odd')

339 is odd


Q3: A student passes the course only if `score >= 60` **and** `attendance >= 0.8`. Given `score = 72` and `attendance = 0.9`, print whether the student passed (expected: `Passed? True`). You must combine a comparison with the logical `and`.  
**Difficulty:** ★★☆☆☆  **Skills:** `comparison` and `and`

In [6]:
# your code here
score = 72
attendance = 0.9
passed = score>=60 and attendance >=0.8
print(passed)
if passed == True:
  print('the student passed')
else:
  print('the student did not pass')

the student passed


Q4: Given `enrolled = ['HUDM5001', 'HUDM5122']` and `grades = {'Ann': 90, 'Bob': 85}`, use `in` / `not in` to print three checks (all should be `True`): is `'HUDM5001'` in `enrolled`? does `'Ann'` have a grade? does `'Cara'` *not* have a grade yet? Remember: `in` on a dict tests its **keys**.  
**Difficulty:** ★★★☆☆  **Skills:** `in` / `not in` (list & dict)

In [7]:
# your code here
enrolled = ['HUDM5001', 'HUDM5122']
grades = {'Ann': 90, 'Bob': 85}
a= 'HUDM5001' in enrolled
b= 'Ann' in grades
c= 'Cara' not in grades
print(f'is HUDM5001 in enrolled {a}, does Ann have a grade {b}, does Cara not have a grade yet {c}')

is HUDM5001 in enrolled True, does Ann have a grade True, does Cara not have a grade yet True


Q5: A year is a leap year when it is divisible by 4, **and** (*not* divisible by 100 **or** divisible by 400). Using only `%`, comparison, and logical operators (no `if`!), print whether `2024` is a leap year (expected: `2024 leap year? True`). Bonus: swap in `1900` (→ False) and `2000` (→ True) to see the 100/400 twist.  
**Difficulty:** ★★★★★  **Skills:** `%`, `and`, `or`, `not`  
Tips:  A year is a leap year `if it is divisible by 4 and not divisible by 100`, **OR** `if it is divisible by 400`.

In [9]:
# your code here
leap_year= 2024%4==0 and (2024%100!=0 or 2024%400==0)
print(f'is 2024 a leap year? {leap_year}')
leap_year2= 1900%4==0 and (1900%100!=0 or 1900%400==0)
print(f'is 1900 a leap year? {leap_year2}')
leap_year3= 2000%4==0 and (2000%100!=0 or 2000%400==0)
print(f'is 2000 a leap year? {leap_year3}')

is 2024 a leap year? True
is 1900 a leap year? False
is 2000 a leap year? True


### 2.2 Input/Output — reading & writing files
You open a file with `open(path, mode)`. Common **modes**: `'r'` read, `'w'` write (overwrite), `'a'` append.
Always prefer the **`with open(...)`** form — it closes the file automatically, even if an error occurs.

**Text files.** Let's write one, then read it back (this runs in your Colab session).

In [10]:
# WRITE
with open('notes.txt', 'w') as file:
    file.write('line 1: hello\n')
    file.write('line 2: programming for data science\n')

# READ
with open('notes.txt', 'r') as file:
    contents = file.read()
print(contents)

line 1: hello
line 2: programming for data science



When you read a txt file with multi-languages or emojis, you can use specifiy the decode method to avoid possible errors: `with open("example.txt", "r", encoding="utf-8") as file:`

**JSON** (JavaScript Object Notation) is text that maps cleanly to Python dicts/lists — the most
common format for web data. Use `json.dump` to write and `json.load` to read.

In [11]:
record = {'name': 'iris study', 'n': 150, 'features': ['sepal', 'petal']}

with open('record.json', 'w') as file:
    json.dump(record, file)

with open('record.json', 'r') as file:
    back = json.load(file)

print(back)
print('features:', back['features'])      # back is a normal dict

{'name': 'iris study', 'n': 150, 'features': ['sepal', 'petal']}
features: ['sepal', 'petal']


**CSV** (comma-separated values) is the everyday data format. We'll read one **straight from the
course GitHub repo** via `DATA_BASE` — no download needed — using pandas (much easier than the raw `csv` module).

In [12]:
wine = pd.read_csv(DATA_BASE + '/wine.csv')
print(type(wine), '| shape:', wine.shape)
print('columns:', list(wine.columns))
wine.head()

<class 'pandas.core.frame.DataFrame'> | shape: (178, 14)
columns: ['class_id', 'alcohol', 'malic_acid', 'ash', 'alcalinity', 'magnesium', 'phenols', 'flavanoids', 'nonflav_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'OD280_OD315', 'proline']


,class_id,alcohol,malic_acid,ash,alcalinity,magnesium,phenols,flavanoids,nonflav_phenols,proanthocyanins,color_intensity,hue,OD280_OD315,proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735


In [13]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=wine)

MessageError: Error: credential propagation was unsuccessful

In [ ]:
# WRITE a CSV: keep just the first two rows and save locally
wine.head(2).to_csv('wine_first_two.csv', index=False)
print(open('wine_first_two.csv').read())

**Paths with `os.path`.** Build and inspect paths portably (works on Mac/Windows/Linux).

In [14]:
print('cwd:', os.getcwd())

some_path = '/Users/clark_kent/data.csv'
print('basename:', os.path.basename(some_path))   # 'data.csv'
print('dirname :', os.path.dirname(some_path))     # '/Users/clark_kent'
print('joined  :', os.path.join('data', 'raw', 'file.csv'))   # OS-correct separator
print('exists? :', os.path.exists('notes.txt'))    # True (we wrote it above)

cwd: /content
basename: data.csv
dirname : /Users/clark_kent
joined  : data/raw/file.csv
exists? : True


#### ✏️ Try It Yourself — Exercise 2

Q1: Write the two lines `hello` and `data science` to a file `myfile.txt`, then read the whole file back with `.read()` and print it. Use the `with open(...)` form.  
**Difficulty:** ★☆☆☆☆  **Skills:** `with open`, `.write` / `.read`

In [17]:
# your code here
with open ('myfile.txt','w') as file:
  file.write('hello\ndata science')
with open ('myfile.txt','r') as file:
  content=file.read()
print(content)

hello
data science


Q2: Given `p = '/Users/clark_kent/projects/data.csv'`, use `os.path` to print (a) the file name, (b) the folder it lives in, and (c) a new path made by joining `'backup'`, `'2026'`, and that file name. No file is created here — this is pure path work.  
**Difficulty:** ★★☆☆☆  **Skills:** `os.path.basename` / `dirname` / `join`

In [18]:
# your code here
import os
p = '/Users/clark_kent/projects/data.csv'
print(os.path.basename(p))
a=str(os.path.basename(p))
print(os.path.dirname(p))
print(os.path.join('backup','2026',a))

data.csv
/Users/clark_kent/projects
backup/2026/data.csv


Q3: Make a dict `student = {'name': 'Ann', 'scores': [90, 85, 88]}`, write it to `student.json` with `json.dump`, then read it back with `json.load` and print the value stored under `'scores'`. Finally confirm the file is really there with `os.path.exists`.  
**Difficulty:** ★★★☆☆  **Skills:** `json.dump` / `json.load`, `os.path.exists`

In [19]:
# your code here
student = {'name': 'Ann', 'scores': [90, 85, 88]}
with open('student.json','w') as file:
  json.dump(student,file)
with open('student.json','r') as file:
  back= json.load(file)
print(back)
print(os.path.exists('student.json'))

{'name': 'Ann', 'scores': [90, 85, 88]}
True


Q4: Read the wine CSV from `DATA_BASE + 'asset/wine.csv'`. Print its `shape` and its column names as a list. Then save just the **first 3 rows** to `wine_head.csv` (no index column) and print that file's text back to check.  
**Difficulty:** ★★★★☆  **Skills:** `pd.read_csv`, `df.to_csv`

In [26]:
# your code here
print(os.path.join(DATA_BASE, 'wine.csv'))
print(pd.read_csv(os.path.join(DATA_BASE, 'wine.csv')).head(3))
print(list(pd.read_csv(os.path.join(DATA_BASE, 'wine.csv')).columns))

https://raw.githubusercontent.com/cgpan/hudm5001/main/asset/wine.csv
   class_id  alcohol  malic_acid   ash  alcalinity  magnesium  phenols  \
0         1    14.23        1.71  2.43        15.6        127     2.80   
1         1    13.20        1.78  2.14        11.2        100     2.65   
2         1    13.16        2.36  2.67        18.6        101     2.80   

   flavanoids  nonflav_phenols  proanthocyanins  color_intensity   hue  \
0        3.06             0.28             2.29             5.64  1.04   
1        2.76             0.26             1.28             4.38  1.05   
2        3.24             0.30             2.81             5.68  1.03   

   OD280_OD315  proline  
0         3.92     1065  
1         3.40     1050  
2         3.17     1185  
['class_id', 'alcohol', 'malic_acid', 'ash', 'alcalinity', 'magnesium', 'phenols', 'flavanoids', 'nonflav_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'OD280_OD315', 'proline']


Q5: From the wine CSV, take its column names as a list and write **that list** to `wine_cols.json` with `json.dump` — JSON stores a list directly, so no loop is needed! Read it back with `json.load`, then print the **first** and **last** column names using list indexing (`[0]` and `[-1]`).  
**Difficulty:** ★★★★★  **Skills:** `json.dump` (a list), list indexing

In [27]:
# your code here
os.path.join(DATA_BASE, 'wine.csv')
wine=pd.read_csv(os.path.join(DATA_BASE, 'wine.csv'))
columns_wine=list(wine.columns)
with open('wine_cols.json','w') as file:
  json.dump(columns_wine,file)
with open('wine_cols.json','r') as file:
  back=json.load(file)
print(back[0],back[-1])

class_id proline


### 2.3 NumPy — fast numeric arrays
**Why NumPy?** A Python list of a million numbers is slow to do math on. NumPy stores numbers in a compact
**`ndarray`** and applies operations to the *whole array at once* (**vectorization**) — far faster and cleaner
than looping.

In [29]:
# A quick taste: 10 random dice rolls in [1, 6]
np.random.seed(0)                    # reproducible randomness
print(np.random.randint(1, 7, 10))

[5 6 1 4 4 4 2 4 6 3]


An **ndarray** is a multidimensional, *homogeneous* (all-one-type), fixed-size grid. Make one from
a list of lists; `.shape` gives `(rows, columns)`.

In [33]:
x = np.array([[2, 3, 1],
              [3, 1, 2]])
print(x)
print('shape:', x.shape)     # (2, 3) -> 2 rows, 3 cols
print('dtype:', x.dtype)
print('dimension',x.ndim)

[[2 3 1]
 [3 1 2]]
shape: (2, 3)
dtype: int64
dimension 2


**Vectorized math** happens *element-wise* — no loop required.

In [31]:
print(x * 2)      # scale every element
print('---')
print(x + x)      # element-wise addition
print('---')
print(1 / x)      # element-wise reciprocal

[[4 6 2]
 [6 2 4]]
---
[[4 6 2]
 [6 2 4]]
---
[[0.5        0.33333333 1.        ]
 [0.33333333 1.         0.5       ]]


**Special arrays** you'll reach for constantly:

In [32]:
print(np.zeros((2, 3)))     # all zeros, shape 2x3
print(np.ones((2, 3)))      # all ones
print(np.identity(3))       # 3x3 identity matrix
print(np.arange(0, 10, 2))  # like range, but an array: [0 2 4 6 8]
print(np.eye(2,3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


**Indexing & slicing** works like lists, extended to multiple dimensions with `[row, col]`.
**Boolean indexing** selects elements that satisfy a condition — the key to filtering data.

In [34]:
np.random.seed(1)
z = np.random.randn(5)          # 5 draws from a standard normal
print('z        :', z.round(2))
print('z[1:3]   :', z[1:3].round(2))      # slice positions 1,2
print('z > 0    :', z > 0)                # a boolean array
print('positives:', z[z > 0].round(2))    # boolean indexing -> keep only z>0

z        : [ 1.62 -0.61 -0.53 -1.07  0.87]
z[1:3]   : [-0.61 -0.53]
z > 0    : [ True False False False  True]
positives: [1.62 0.87]


In [35]:
# 2-D indexing: rows then columns
m = np.array([[10, 20, 30],
              [40, 50, 60]])
print('element [0,2]:', m[0, 2])      # 30
print('first row    :', m[0, :])      # [10 20 30]
print('last column  :', m[:, -1])     # [30 60]

# common summaries
print('mean:', m.mean(), '| max:', m.max(), '| column sums:', m.sum(axis=0))

element [0,2]: 30
first row    : [10 20 30]
last column  : [30 60]
mean: 35.0 | max: 60 | column sums: [50 70 90]


#### ✏️ Try It Yourself — Exercise 3
Make an array `w = np.arange(1, 11)` (the numbers 1–10). Using **boolean indexing**, print (a) only the even numbers and (b) the mean of the numbers greater than 5.

In [38]:
# Your code here
import numpy as np
w = np.arange(1, 11)
print(w[w%2==0])
print(w[w>5].mean())

[ 2  4  6  8 10]
8.0


<details>
<summary>▶ Show solution</summary>

```python
w = np.arange(1, 11)
print(w[w % 2 == 0])           # even numbers
print(w[w > 5].mean())        # mean of those > 5
```

</details>

---
## 3. Conclusions & Key Takeaways
- `//` floors, `%` gives the remainder, `**` is power; `/` always returns a float.
- `is` compares **identity** (same object); `==` compares **value**. They're not the same!
- Always read/write files with **`with open(path, mode)`** so they close safely.
- **JSON ↔ dict** via `json.load`/`json.dump`; **CSV** is easiest with `pd.read_csv` / `df.to_csv`.
- You can read data **directly from a URL** with pandas — that's how these notebooks stay zero-setup.
- NumPy's **ndarray** enables **vectorized** element-wise math — fast and loop-free.
- **Boolean indexing** (`arr[arr > 0]`) is the foundation of data filtering in NumPy and pandas.

### 🧾 Quick Reference
| Task | Code |
|---|---|
| floor / remainder | `a // b`, `a % b` |
| read text safely | `with open(p) as f: f.read()` |
| read CSV from URL | `pd.read_csv(DATA_BASE + '...')` |
| array from list | `np.array([[1,2],[3,4]])` |
| zeros / ones / identity | `np.zeros((r,c))`, `np.ones(...)`, `np.identity(n)` |
| element-wise math | `x * 2`, `x + y`, `1 / x` |
| boolean filter | `z[z > 0]` |
| stats | `arr.mean()`, `.sum(axis=0)`, `.max()` |

### ⏭️ Coming Up Next
**Week 4 — pandas!** The library you'll use most: labeled tables (DataFrames) built on top of NumPy. Read McKinney Ch 5.

### 📌 This Week's Assignment
Still Assignment_01, Due Sept.28 at 11:59pm.  
Assignment_02 is also available on both Canvas and [course GitHub](https://github.com/cgpan/hudm5001).  
Assignment_02 is due Oct. 05 at 11:59pm.

> 💡 **Tip:** make a copy in Colab (*File ▸ Save a copy in Drive*) and add your own notes — experimenting in the code cells is the fastest way to learn.